{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.babbaj",
    "module": "nether-pathfinder",
    "version": "0.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "nether-pathfinder-0.20.jar",
          "url": "nether-pathfinder-0.20.jar",
          "size": 1394928,
          "sha512": "61684c1808a40c70278b0bbd1c21ec5ae0a22b5cdc8da59a2df436663b35299fda64c48b8ee37cdfa37720193482fed880a1ddb4b4db77d96355d5e2218098c2",
          "sha256": "66f1b18ef3f4895412411380a5fa43244038c43e37bd8123c13f487e5ecd6b69",
          "sha1": "43d2d9fbc4cc5d60df682b0643638fbd544b3857",
          "md5": "0201ad78b9c3b3d0f2e60dc4b7c9a2e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nether-pathfinder-0.20.jar",
          "url": "nether-pathfinder-0.20.jar",
          "size": 1394928,
          "sha512": "61684c1808a40c70278b0bbd1c21ec5ae0a22b5cdc8da59a2df436663b35299fda64c48b8ee37cdfa37720193482fed880a1ddb4b4db77d96355d5e2218098c2",
          "sha256": "66f1b18ef3f4895412411380a5fa43244038c43e37bd8123c13f487e5ecd6b69",
          "sha1": "43d2d9fbc4cc5d60df682b0643638fbd544b3857",
          "md5": "0201ad78b9c3b3d0f2e60dc4b7c9a2e2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "nether-pathfinder-0.20-sources.jar",
          "url": "nether-pathfinder-0.20-sources.jar",
          "size": 2471,
          "sha512": "c27016dd0e95ad1c57b6f68206accf68de82f1142297f6a6962a73799c55351c559ba2eeec1bf669dcb039ddbfcaa438cf5d2a799aba90c22fea62c91941583e",
          "sha256": "b69adb1a47d95c3c0aad5a571c7a31a23ed643a86826c5aa3d979e2502ffd520",
          "sha1": "71b2e2f82c0f3c2346c7feaa55dd0c3979b742b3",
          "md5": "b592e697583d8dab92a454f598908ac8"
        }
      ]
    }
  ]
}
